---
title: "Clustering"
author: "Dr. Stephen W. Thomas, Queen's University"
output:
  pdf_document:
    highlight: pygments
    number_sections: yes
    toc: no
    toc_depth: '2'
---



```{r}
library(dplyr)
library(ggplot2)
library(readr)
library(extrafont)
library(ggthemes)
library(caret)
library(cluster) # For preprocessing
library(factoextra) # for elbow plots
library(amap) # For distance metrics
library(stylo) # For cosine distance
loadfonts(quiet = T)
```

# Load Data

```{r}
dat <- read_csv("data/Mall_Customers_With_output.csv")
str(dat)
dat %>%
  select(CustomerID, Genre, Age, AnnualIncome, SpendingScore) %>%
  head(n=15)
```
```{r}
plotClust = function(df, colorCol) {
  ggplot(df, aes(x=AnnualIncome, y=SpendingScore)) + 
  geom_point(aes(color=factor(colorCol)), size=6) +
  geom_rangeframe() + 
  theme_tufte(base_family="Calibri") + 
  #theme(legend.position="none") + 
  theme(axis.title.x = element_text(colour="grey20",size=30,face="plain")) + 
  theme(axis.title.y = element_text(colour="grey20",size=30,face="plain")) + 
  theme(axis.text.x = element_text(colour="grey20",size=20,face="plain")) + 
  theme(axis.text.y = element_text(colour="grey20",size=20,face="plain")) +
  labs(x = "Annual Income (K)", y ="Spending Score") 
  
}
```

# Plot the data

```{r}
iwidth = 10
iheight = 7

theme_set(theme_gray(base_size = 32))


ggplot(dat, aes(x=AnnualIncome, y=SpendingScore)) + 
  geom_point(color="black", size=10) +
  geom_rangeframe() + 
  theme_tufte(base_family="Calibri") + 
  theme(legend.position="none") + 
  theme(axis.title.x = element_text(colour="grey20",size=40,face="plain")) + 
  theme(axis.title.y = element_text(colour="grey20",size=40,face="plain")) + 
  theme(axis.text.x = element_text(colour="grey20",size=32,face="plain")) + 
  theme(axis.text.y = element_text(colour="grey20",size=32,face="plain")) +
  labs(x = "Annual Income (K)", y ="Spending Score") 
  
#ggsave(file="out/cluster_1.png", width=iwidth, height=iheight)

```

# Scaling the data

```{r}
pre = preProcess(dat[,c("Age", "AnnualIncome", "SpendingScore")], method="range")
dat.scaled = predict(pre, dat, method=c("range"))
head(dat)
head(dat.scaled)
dat.scaled %>%
  select(CustomerID, Genre, Age, AnnualIncome, SpendingScore) %>%
  head(n=15)
```

# Playing with Distance Metrics

```{r}

df = dat.scaled[,c("Age", "AnnualIncome", "SpendingScore")]
dd_euc = as.matrix(Dist(df, method = "euclidean"))
dd_man = as.matrix(Dist(df, method = "manhattan"))
dd_cos = as.matrix(dist.cosine(as.matrix(df)))


# Check ou the three closest and farthest people from Customer ID 1
print("euc")
n = ncol(dd_euc)
idx = order(dd_euc[1,])[2:4]
idx
dd_euc[1, idx]
df[c(1, idx),]
idx_long = order(dd_euc[1,])[(n-2):n]
idx_long
dd_euc[1, idx_long]
df[c(1, idx_long),]


print("man")
n = ncol(dd_man)
idx = order(dd_man[1,])[2:4]
idx
dd_man[1, idx]
df[c(1, idx),]
idx_long = order(dd_man[1,])[(n-2):n]
idx_long
dd_man[1, idx_long]
df[c(1, idx_long),]


print("cos")
n = ncol(dd_cos)
idx = order(dd_cos[1,])[2:4]
idx
dd_cos[1, idx]
df[c(1, idx),]
idx_long = order(dd_cos[1,])[(n-2):n]
idx_long
dd_cos[1, idx_long]
df[c(1, idx_long),]

```


# K-means

```{r}
set.seed(123)

clusters = kmeans(dat.scaled[,c("AnnualIncome", "SpendingScore")], centers=5, nstart=10)
dat.scaled$kmeans5 = clusters$cluster
clusters$tot.withinss
plotClust(dat.scaled, clusters$cluster)
ggsave(file="out/cluster_kmeans5.png", width=iwidth, height=iheight)
head(dat.scaled, n=15)
clusters$centers
clusters$size


clusters = kmeans(dat.scaled[,c("AnnualIncome", "SpendingScore")], 
                  centers=3, 
                  nstart=10)
dat.scaled$kmeans3 = clusters$cluster
clusters$tot.withinss
head(dat.scaled, n=15)
plotClust(dat.scaled, clusters$cluster)
ggsave(file="out/cluster_kmeans3.png", width=iwidth, height=iheight)

clusters = kmeans(dat.scaled[,c("AnnualIncome", "SpendingScore")], centers=10, nstart=10)
plotClust(dat, clusters$cluster)

#ggsave(file="out/cluster_kmeans1.png", width=iwidth, height=iheight)
```

## Elbow Plot

```{r}
set.seed(123)
fviz_nbclust(dat.scaled[,c("AnnualIncome", "SpendingScore")], kmeans, method = "silhouette", k.max=15)
ggsave(file="out/kmeans_sil.png", width=6, height=4)

fviz_nbclust(dat.scaled[,c("AnnualIncome", "SpendingScore")], kmeans, method = "wss", k.max=15)
ggsave(file="out/kmeans_wss.png", width=6, height=4)
```

## Which Distance Measure?

```{r}
df = dat.scaled[,c("AnnualIncome", "SpendingScore")]
dd_euc = dist(df, method = "euclidean")
dd_man = dist(df, method = "manhattan")
dd_min = dist(df, method = "minkowski")

k <- 5

set.seed(123)

res = data.frame(method=character(), wss=numeric(), betweenss=numeric())

clusters = kmeans(dd_euc, k, nstart=50)
res = rbind(res, data.frame(method="euclidean", wss=clusters$tot.withinss, betweenness=clusters$betweenss))
plotClust(df, clusters$cluster)
ggsave(file="out/kmeans_euc.png", width=iwidth, height=iheight)

clusters = kmeans(dd_man, k, nstart=50)
res = rbind(res, data.frame(method="manhattan", wss=clusters$tot.withinss, betweenness=clusters$betweenss))
plotClust(df, clusters$cluster)
ggsave(file="out/kmeans_man.png", width=iwidth, height=iheight)

clusters = kmeans(dd_min, k, nstart=50)
res = rbind(res, data.frame(method="minkowski", wss=clusters$tot.withinss, betweenness=clusters$betweenss))
plotClust(df, clusters$cluster)
ggsave(file="out/kmeans_min.png", width=iwidth, height=iheight)

res
```





# DBSCAN

```{r}
library(dbscan)

set.seed(123)

kNNdistplot(dat.scaled[,c("AnnualIncome", "SpendingScore")], k = 3)
# Right Click on the image below, then "Copy"

clusters = dbscan(dat.scaled[,c("Age", "AnnualIncome", "SpendingScore")], 
                  minPts = 3, 
                  eps = .14)
dat.scaled$dbscan = clusters$cluster

plotClust(dat.scaled, dat.scaled$dbscan)
ggsave(file="out/dbscan.png", width=iwidth, height=iheight)

```


# Hierarchical


```{r}
set.seed(123)

clusters = hclust(dist(dat.scaled[,c("AnnualIncome", "SpendingScore")])) 
hcd <- as.dendrogram(clusters)
plot(hcd)
plot(hcd, xlim = c(1, 20), ylim = c(0,0.4))


dat.scaled$hclust5 = cutree(clusters, 5)
plotClust(dat.scaled, dat.scaled$hclust5)
ggsave(file="out/cluster_hclust5.png", width=iwidth, height=iheight)

dat.scaled$hclust3 = cutree(clusters, 3)
plotClust(dat.scaled, dat.scaled$hclust3)
ggsave(file="out/cluster_hclust3.png", width=iwidth, height=iheight)

dat.scaled$hclust8 = cutree(clusters, 8)
plotClust(dat.scaled, dat.scaled$hclust8)
ggsave(file="out/cluster_hclust8.png", width=iwidth, height=iheight)
```
